### ISSUE TITLE
После обновления от ВК скрипт перестал работать

### ISSUE THREAD

**Issue by rkoten** [KJ86/VKDownloadMedia#4]
На 19.07.2017, скрипт не может получить метаданные аудиозаписи: ![](https://i.imgur.com/y6efC2U.png)
Также, при закачке ВК подменивает mp3-файл на заглушку, в которой записано сообщение в роде "Пользуйтесь официальными приложениями ВК для прослушивания музыки".

**Comment by KJ86** [comment]
Исправлено. Версия 5.2
Спасибо.
